extract = 'total_dyn_inst: (\d+)'
benchmarks = '../benchmarks/**/*.bril'

[runs.baseline]
pipeline = [
    "bril2json",
    "brili -p {args}",
]

[runs.dead_store]
pipeline = [
    "bril2json",
    "python aliasing.py",
    "brili -p {args}",
]